dataSource:
  -
   db_file_path: device.db
   name: device
   type: sqlite
   slow_sql: 100 #ms
kafka :
  host: 218.0.49.239
  port: 9092
redis:
  -
    host: 127.0.0.1:6379
    password:
    db: 10
    name: test1
  -
    host: 127.0.0.1:6379
    password:
    db: 10
    name: test2